# Generated by Django 4.1.3 on 2022-12-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="excerpt",
            field=models.TextField(null=True),
        ),
    ]
